/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface AplazamePayByWebPost {
    /**
     * Custom data that you can add to this item
     */
    tag?: string;

    /**
     * Whether to save or not the card for future use. SaveCard and CardId are mutually exclusive
     */
    userId?: number;

    /**
     * The ID of the wallet where money will be credited
     */
    creditedWalletId?: string;

    /**
     * Information about the funds that are being debited
     */
    debitedFunds: models.Money;

    /**
     * Information about the fees that were taken by the client for this transaction (and were hence transferred to the Client's platform wallet)
     */
    fees?: models.Money;

    shipping?: models.Money;

    /**
     * Dirección (relativa a la tienda) a la que redirigirá en caso de error en el pago.
     */
    cancelUrl: string;

    /**
     * Dirección (relativa a la tienda) a la que redirigirá cuando se haya completado el pago.
     */
    successUrl: string;

    /**
     * Dirección a la que se redirigirá el usuario si escoge volver a la tienda (por omisión '/').
     */
    checkoutUrl?: string;

    orderItems: Array<models.AplazameOrderItem>;

    /**
     * Customer data.  Optional user info. If it is not set, Marketpay will try to use the data it does currently have about the user, but it will fail if existing data is not enough.
     */
    customer: models.Customer;

}
