/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BankAccountIbanPost {
    /**
     * The IBAN of the bank account
     */
    iBAN?: string;

    /**
     * The BIC of the bank account
     */
    bIC?: string;

    /**
     * Custom data that you can add to this item
     */
    tag?: string;

    /**
     * The address of the owner of the bank account
     */
    ownerAddress?: models.Address;

    /**
     * The name of the owner of the bank account
     */
    ownerName?: string;

}
