/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BankAccountResponseUs {
    /**
     * The account number of the bank account. US account numbers must be digits only
     */
    accountNumber?: string;

    /**
     * The ABA of the bank account. Must be numbers only, and 9 digits long
     */
    aBA?: string;

    /**
     * The type of account
     */
    depositAccountType?: BankAccountResponseUs.DepositAccountTypeEnum;

    /**
     * The type of bank account
     */
    type?: BankAccountResponseUs.TypeEnum;

    /**
     * The address of the owner of the bank account
     */
    ownerAddress?: models.Address;

    /**
     * The name of the owner of the bank account
     */
    ownerName?: string;

    /**
     * The object owner's UserId
     */
    userId?: string;

    /**
     * Whether the bank account is active or not
     */
    active?: boolean;

    id?: string;

    creationDate?: number;

    tag?: string;

}
export namespace BankAccountResponseUs {
    export enum DepositAccountTypeEnum {
        NotSpecified = <any> 'NotSpecified',
        CHECKING = <any> 'CHECKING',
        SAVINGS = <any> 'SAVINGS'
    }
    export enum TypeEnum {
        IBAN = <any> 'IBAN',
        GB = <any> 'GB',
        US = <any> 'US',
        CA = <any> 'CA',
        OTHER = <any> 'OTHER'
    }
}
