/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BankAccountCaPost {
    /**
     * The branch code of the bank where the bank account. Must be numbers only, and 5 digits long
     */
    branchCode?: string;

    /**
     * The institution number of the bank account. Must be numbers only, and 3 or 4 digits long
     */
    institutionNumber?: string;

    /**
     * The account number of the bank account. Must be numbers only. Canadian account numbers must be a maximum of 20 digits
     */
    accountNumber?: string;

    /**
     * The name of the bank where the account is held. Must be letters or numbers only and maximum 50 characters long
     */
    bankName?: string;

    /**
     * Custom data that you can add to this item
     */
    tag?: string;

    /**
     * The address of the owner of the bank account
     */
    ownerAddress?: models.Address;

    /**
     * The name of the owner of the bank account
     */
    ownerName?: string;

}
