/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BankAccountGbPost {
    /**
     * The sort code of the bank account. Must be numbers only, and 6 digits long
     */
    sortCode?: string;

    /**
     * The account number of the bank account. Must be numbers only. GB account numbers must be 8 digits long
     */
    accountNumber?: string;

    /**
     * Custom data that you can add to this item
     */
    tag?: string;

    /**
     * The address of the owner of the bank account
     */
    ownerAddress?: models.Address;

    /**
     * The name of the owner of the bank account
     */
    ownerName?: string;

}
