/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BankAccountUsPost {
    /**
     * The account number of the bank account. US account numbers must be digits only
     */
    accountNumber?: string;

    /**
     * The ABA of the bank account. Must be numbers only, and 9 digits long
     */
    aBA?: string;

    /**
     * The type of account
     */
    depositAccountType?: BankAccountUsPost.DepositAccountTypeEnum;

    /**
     * Custom data that you can add to this item
     */
    tag?: string;

    /**
     * The address of the owner of the bank account
     */
    ownerAddress?: models.Address;

    /**
     * The name of the owner of the bank account
     */
    ownerName?: string;

}
export namespace BankAccountUsPost {
    export enum DepositAccountTypeEnum {
        NotSpecified = <any> 'NotSpecified',
        CHECKING = <any> 'CHECKING',
        SAVINGS = <any> 'SAVINGS'
    }
}
