/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PayOutBankWireResponse {
    authorId?: string;

    creditedUserId?: string;

    debitedFunds?: models.Money;

    creditedFunds?: models.Money;

    fees?: models.Money;

    status?: PayOutBankWireResponse.StatusEnum;

    resultCode?: string;

    resultMessage?: string;

    executionDate?: number;

    type?: PayOutBankWireResponse.TypeEnum;

    nature?: PayOutBankWireResponse.NatureEnum;

    debitedWalletId?: string;

    creditedWalletId?: string;

    paymentType?: PayOutBankWireResponse.PaymentTypeEnum;

    bankAccountId?: string;

    bankWireRef?: string;

    id?: string;

    creationDate?: number;

    tag?: string;

}
export namespace PayOutBankWireResponse {
    export enum StatusEnum {
        CREATED = <any> 'CREATED',
        SUCCEEDED = <any> 'SUCCEEDED',
        FAILED = <any> 'FAILED'
    }
    export enum TypeEnum {
        PAYIN = <any> 'PAYIN',
        PAYOUT = <any> 'PAYOUT',
        TRANSFER = <any> 'TRANSFER'
    }
    export enum NatureEnum {
        REGULAR = <any> 'REGULAR',
        REFUND = <any> 'REFUND',
        REPUDIATION = <any> 'REPUDIATION',
        SETTLEMENT = <any> 'SETTLEMENT'
    }
    export enum PaymentTypeEnum {
        NotSpecified = <any> 'NotSpecified',
        BANKWIRE = <any> 'BANK_WIRE'
    }
}
