/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RedsysPayByWebResponse {
    /**
     * Id of the payment
     */
    payInId?: string;

    /**
     * Url to post from the user's browser
     */
    url?: string;

    /**
     * This paramater must be include in the Post to the Url
     */
    dsSignatureVersion?: string;

    /**
     * This paramater must be include in the Post to the Url
     */
    dsMerchantParameters?: string;

    /**
     * This paramater must be include in the Post to the Url
     */
    dsSignature?: string;

}
