/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RedsysPayByWebPost {
    /**
     * Custom data that you can add to this item
     */
    tag?: string;

    /**
     * Whether to save or not the card for future use. SaveCard and CardId are mutually exclusive
     */
    saveCard?: boolean;

    /**
     * The id of a previous saved card. SaveCard and CardId are mutually exclusive
     */
    cardId?: string;

    /**
     * The ID of the wallet where money will be credited
     */
    creditedWalletId: string;

    /**
     * A custom description to appear on the user's bank statement. It can be up to 10 characters long, and can only include alphanumeric characters or spaces
     */
    statementDescriptor?: string;

    /**
     * Dirección (relativa a la tienda) a la que redirigirá cuando se haya completado el pago.
     */
    successUrl: string;

    /**
     * Url to redirect the browser in case the payment is completed successfully
     */
    urlOk?: string;

    /**
     * Dirección (relativa a la tienda) a la que redirigirá en caso de error en el pago.
     */
    cancelUrl: string;

    /**
     * Url to redirect the browser in case the payment is not completed successfully
     */
    urlKo?: string;

    /**
     * Information about the funds that are being debited
     */
    debitedFunds: models.Money;

    /**
     * Information about the fees that were taken by the client for this transaction (and were hence transferred to the Client's platform wallet)
     */
    fees: models.Money;

}
