/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RedsysPreauthorizeResponse {
    /**
     * Information about the funds that are being debited
     */
    debitedFunds?: models.Money;

    /**
     * The status of the transaction
     */
    status?: RedsysPreauthorizeResponse.StatusEnum;

    /**
     * Status of the payment
     */
    paymentStatus?: RedsysPreauthorizeResponse.PaymentStatusEnum;

    /**
     * When the transaction happened
     */
    executionDate?: number;

    /**
     * The result code
     */
    resultCode?: string;

    /**
     * A verbal explanation of the ResultCode
     */
    resultMessage?: string;

    /**
     * The type of execution for the payin
     */
    executionType?: RedsysPreauthorizeResponse.ExecutionTypeEnum;

    /**
     * The Id of the card saved, if any.
     */
    cardId?: string;

    /**
     * A custom description to appear on the user's bank statement. It can be up to 10 characters long, and can only include alphanumeric characters or spaces
     */
    statementDescriptor?: string;

    /**
     * A user's ID
     */
    authorId?: string;

    /**
     * The Id of the associated PayIn
     */
    payInId?: string;

    /**
     * Redsys related data
     */
    provider?: models.PreauthorizationRedsysData;

    id?: string;

    creationDate?: number;

    tag?: string;

}
export namespace RedsysPreauthorizeResponse {
    export enum StatusEnum {
        CREATED = <any> 'CREATED',
        SUCCEEDED = <any> 'SUCCEEDED',
        FAILED = <any> 'FAILED'
    }
    export enum PaymentStatusEnum {
        NotSpecified = <any> 'NotSpecified',
        WAITING = <any> 'WAITING',
        CANCELED = <any> 'CANCELED',
        EXPIRED = <any> 'EXPIRED',
        VALIDATED = <any> 'VALIDATED'
    }
    export enum ExecutionTypeEnum {
        NotSpecified = <any> 'NotSpecified',
        WEB = <any> 'WEB',
        DIRECT = <any> 'DIRECT'
    }
}
