/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RefundReason {
    /**
     * The type of reason for refusal
     */
    type?: RefundReason.TypeEnum;

    /**
     * The message accompanying a refusal
     */
    message?: string;

}
export namespace RefundReason {
    export enum TypeEnum {
        NotSpecified = <any> 'NotSpecified',
        BANKACCOUNTINCORRECT = <any> 'BANKACCOUNT_INCORRECT',
        BANKACCOUNTHASBEENCLOSED = <any> 'BANKACCOUNT_HAS_BEEN_CLOSED',
        OWNERDOTNOTMATCHBANKACCOUNT = <any> 'OWNER_DOT_NOT_MATCH_BANKACCOUNT',
        WITHDRAWALIMPOSSIBLEONSAVINGSACCOUNTS = <any> 'WITHDRAWAL_IMPOSSIBLE_ON_SAVINGS_ACCOUNTS',
        INITIALIZEDBYCLIENT = <any> 'INITIALIZED_BY_CLIENT',
        OTHER = <any> 'OTHER'
    }
}
