/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SeurShipmentPost {
    /**
     * Custom data that you can add to this item
     */
    tag?: string;

    /**
     * 
     */
    pickUpDate?: number;

    /**
     * 
     */
    sender?: models.ShipmentActor;

    /**
     * 
     */
    receiver?: models.ShipmentActor;

    /**
     * The ID of the user sending the package
     */
    senderUserId?: string;

    /**
     * The ID of the user sending the package
     */
    receiverUserId?: string;

    /**
     * 
     */
    product?: models.Product;

}
