/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SeurShipmentResponse {
    /**
     * NumRecogida. Utilizar el id de base de datos
     */
    locatorNumber?: string;

    /**
     * Tasacion
     */
    quotation?: number;

    /**
     * The status of the transaction
     */
    status?: SeurShipmentResponse.StatusEnum;

    /**
     * 
     */
    statusPickUp?: SeurShipmentResponse.StatusPickUpEnum;

    /**
     * 
     */
    statusPickUpCode?: string;

    /**
     * 
     */
    statusDelivery?: SeurShipmentResponse.StatusDeliveryEnum;

    /**
     * 
     */
    statusDeliveryCode?: string;

    id?: string;

    creationDate?: number;

    tag?: string;

}
export namespace SeurShipmentResponse {
    export enum StatusEnum {
        CREATED = <any> 'CREATED',
        SUCCEEDED = <any> 'SUCCEEDED',
        FAILED = <any> 'FAILED',
        CANCELED = <any> 'CANCELED'
    }
    export enum StatusPickUpEnum {
        Unknown = <any> 'Unknown',
        Ready = <any> 'Ready',
        Started = <any> 'Started',
        Failed = <any> 'Failed',
        Picked = <any> 'Picked'
    }
    export enum StatusDeliveryEnum {
        Unknown = <any> 'Unknown',
        Ready = <any> 'Ready',
        Delivered = <any> 'Delivered'
    }
}
