/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TransferPost {
    /**
     * Custom data that you can add to this item
     */
    tag?: string;

    /**
     * The user ID who was credited
     */
    creditedUserId?: string;

    /**
     * Information about the funds that are being debited
     */
    debitedFunds?: models.Money;

    /**
     * Information about the fees that were taken by the client for this transaction (and were hence transferred to the Client's platform wallet)
     */
    fees?: models.Money;

    /**
     * The ID of the wallet that was debited
     */
    debitedWalletId?: string;

    /**
     * The ID of the wallet where money will be credited
     */
    creditedWalletId?: string;

}
