/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface UniversalPayPayByWebPost {
    /**
     * Information about the funds that are being debited
     */
    debitedFunds: models.Money;

    /**
     * Information about the fees that were taken by the client for this transaction (and were hence transferred to the Client's platform wallet)
     */
    fees: models.Money;

    cardId?: string;

    saveCard?: boolean;

    statementDescriptor: string;

    /**
     * Custom data that you can add to this item
     */
    tag?: string;

    /**
     * The ID of the wallet where money will be credited
     */
    creditedWalletId: string;

    secureMode?: UniversalPayPayByWebPost.SecureModeEnum;

    /**
     * Url to redirect the browser in case the payment is completed successfully
     */
    successUrl?: string;

    /**
     * Url to redirect the browser in case the payment is not completed successfully
     */
    cancelUrl?: string;

    /**
     * Defaults to false (show thank you page) Forced to true for iframe
     */
    autoReturn?: boolean;

    /**
     * Valid values are ES, EN, FR
     */
    language?: UniversalPayPayByWebPost.LanguageEnum;

    customer: models.CustomerDetail;

}
export namespace UniversalPayPayByWebPost {
    export enum SecureModeEnum {
        NotSpecified = <any> 'NotSpecified',
        DEFAULT = <any> 'DEFAULT',
        FORCE = <any> 'FORCE'
    }
    export enum LanguageEnum {
        NotSpecified = <any> 'NotSpecified',
        DE = <any> 'DE',
        EN = <any> 'EN',
        DA = <any> 'DA',
        ES = <any> 'ES',
        ET = <any> 'ET',
        FI = <any> 'FI',
        FR = <any> 'FR',
        EL = <any> 'EL',
        HU = <any> 'HU',
        IT = <any> 'IT',
        NL = <any> 'NL',
        NO = <any> 'NO',
        PL = <any> 'PL',
        PT = <any> 'PT',
        SK = <any> 'SK',
        SV = <any> 'SV',
        CS = <any> 'CS'
    }
}
