/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface UserResponse {
    /**
     * Type of user
     */
    personType?: UserResponse.PersonTypeEnum;

    /**
     * 
     */
    kYCLevel?: UserResponse.KYCLevelEnum;

    id?: string;

    creationDate?: number;

    tag?: string;

}
export namespace UserResponse {
    export enum PersonTypeEnum {
        Natural = <any> 'Natural',
        Legal = <any> 'Legal',
        Fees = <any> 'Fees'
    }
    export enum KYCLevelEnum {
        NotSpecified = <any> 'NotSpecified',
        LIGHT = <any> 'LIGHT',
        REGULAR = <any> 'REGULAR'
    }
}
