export * from './CardsApi';
import { CardsApi }  from './CardsApi';
export * from './PayInsAplazameApi';
import { PayInsAplazameApi }  from './PayInsAplazameApi';
export * from './PayInsRedsysApi';
import { PayInsRedsysApi }  from './PayInsRedsysApi';
export * from './PayInsUniversalPayApi';
import { PayInsUniversalPayApi }  from './PayInsUniversalPayApi';
export * from './PayOutsApi';
import { PayOutsApi }  from './PayOutsApi';
export * from './RefundsApi';
import { RefundsApi }  from './RefundsApi';
export * from './ShipmentSeurApi';
import { ShipmentSeurApi }  from './ShipmentSeurApi';
export * from './TransfersApi';
import { TransfersApi }  from './TransfersApi';
export * from './UsersApi';
import { UsersApi }  from './UsersApi';
export * from './WalletsApi';
import { WalletsApi }  from './WalletsApi';
export const APIS = [ CardsApi, PayInsAplazameApi, PayInsRedsysApi, PayInsUniversalPayApi, PayOutsApi, RefundsApi, ShipmentSeurApi, TransfersApi, UsersApi, WalletsApi, ];
