/**
 * MarketPay API
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class PayInsRedsysApi {
    protected basePath = 'https://localhost/';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * View a Redsys payment
     * 
     * @param payInId The Id of a payment
     */
    public payInsRedsysRedsysGetPayment(payInId: number, extraHttpRequestParams?: any): Observable<models.RedsysPayInsResponse> {
        return this.payInsRedsysRedsysGetPaymentWithHttpInfo(payInId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * View a Redsys Preauthorization
     * 
     * @param preauthorizationId The Id of a Redsys Preauthorization
     */
    public payInsRedsysRedsysGetPreauthorization(preauthorizationId: number, extraHttpRequestParams?: any): Observable<models.RedsysPreauthorizeResponse> {
        return this.payInsRedsysRedsysGetPreauthorizationWithHttpInfo(preauthorizationId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Create a Redsys PayIn Request
     * Prepares a payment on Redsys. The data returned is used to show the Redsys interface to the user.  Once the payment is done, the user will be redirected to one of UrlOk or UrlKo passed parameters.  In order to redirect the user, a Post request with Content-Type of application/x-www-form-urlencoded must be executed from the user&#39;s browser.  Below there is an example of a request where the params surrounded by curly braces have to be replaced with the response&#39;s params.  curl -X POST -H \&quot;Content-Type: application/x-www-form-urlencoded\&quot; -H \&quot;Accept: text/html,application/xhtml+xml,application/xml;q&#x3D;0.9,image/webp,*_/_*;q&#x3D;0.8\&quot; -H \&quot;Cache-Control: no-cache\&quot; -H \&quot;Postman-Token: c313f10b-0de1-227e-53d2-f721f25cd79d\&quot; -d &#39;Ds_SignatureVersion&#x3D;{Ds_SignatureVersion}&amp;amp;Ds_MerchantParameters&#x3D;{Ds_MerchantParameters}&amp;amp;Ds_Signature&#x3D;{Ds_Signature}&#39; \&quot;{Url}\&quot;
     * @param redsysPayIn Redsys PayIn Request Object params
     */
    public payInsRedsysRedsysPostPaymentByWeb(redsysPayIn?: models.RedsysPayByWebPost, extraHttpRequestParams?: any): Observable<models.RedsysPayByWebResponse> {
        return this.payInsRedsysRedsysPostPaymentByWebWithHttpInfo(redsysPayIn, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Create a Redsys Preauthorization Request
     * Prepares a preauthorization on Redsys. The data returned is used to show the Redsys interface to the user.  Once the preauthoriation is done, the user will be redirected to one of UrlOk or UrlKo passed parameters.  In order to redirect the user, a Post request with Content-Type of application/x-www-form-urlencoded must be executed from the user&#39;s browser.  Below there is an example of a request where the params surrounded by curly braces have to be replaced with the response&#39;s params.  curl -X POST -H \&quot;Content-Type: application/x-www-form-urlencoded\&quot; -H \&quot;Accept: text/html,application/xhtml+xml,application/xml;q&#x3D;0.9,image/webp,*_/_*;q&#x3D;0.8\&quot; -H \&quot;Cache-Control: no-cache\&quot; -H \&quot;Postman-Token: c313f10b-0de1-227e-53d2-f721f25cd79d\&quot; -d &#39;Ds_SignatureVersion&#x3D;{Ds_SignatureVersion}&amp;amp;Ds_MerchantParameters&#x3D;{Ds_MerchantParameters}&amp;amp;Ds_Signature&#x3D;{Ds_Signature}&#39; \&quot;{Url}\&quot;
     * @param redsysPreauthorization RedsysPreauthorization Object params
     */
    public payInsRedsysRedsysPostPreauthorizationByWeb(redsysPreauthorization?: models.RedsysPreauthorizeByWebPost, extraHttpRequestParams?: any): Observable<models.RedsysPreauthorizeByWebResponse> {
        return this.payInsRedsysRedsysPostPreauthorizationByWebWithHttpInfo(redsysPreauthorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Cancels a Preauthorization
     * 
     * @param preauthorizationId The Id of a Redsys PreauthorizationCancellation
     * @param redsysPreauthorizationCancellation PreauthorizationCancellation Object params
     */
    public payInsRedsysRedsysPostPreauthorizationCancellation(preauthorizationId: number, redsysPreauthorizationCancellation?: models.RedsysPreauthorizationCancellationPost, extraHttpRequestParams?: any): Observable<models.RedsysPreauthorizationCancellationResponse> {
        return this.payInsRedsysRedsysPostPreauthorizationCancellationWithHttpInfo(preauthorizationId, redsysPreauthorizationCancellation, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Confirms a Preauthorization
     * 
     * @param preauthorizationId The Id of a Redsys PreauthorizationConfirmation
     * @param redsysPreauthorizationConfirmation PreauthorizationConfirmation Object params
     */
    public payInsRedsysRedsysPostPreauthorizationConfirmation(preauthorizationId: number, redsysPreauthorizationConfirmation?: models.RedsysPreauthorizationConfirmationPost, extraHttpRequestParams?: any): Observable<models.RedsysPreauthorizationConfirmationResponse> {
        return this.payInsRedsysRedsysPostPreauthorizationConfirmationWithHttpInfo(preauthorizationId, redsysPreauthorizationConfirmation, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Create a Redsys Payment Refund
     * A PayIn Refund is a request to reimburse a user on their payment card. The money which has already been paid will automatically go back to the user’s bank account.              Minimum amount to refund is 1€.              If you&#39;re doing a partial Refund, note that you can only refund the same amount on the same transaction once per day (this is to prevent unintended duplicate refunds). After 24h you can do another refund of the same amount on the same transaction. If it is a different amount on the same transaction, there is not this limit.              If you do not specify DebitedFunds and Fees parameters, it will automatically fully refund the PayIn. However if you do provide one or the other, you must provide both. Note that Fees must be negative if you wish to refund them - adding a positive value for the Fees is a way to charge your customers for the Refund (in the same way you might for a PayIn, Transfer or any other Transaction
     * @param payInId The Id of a PayIn
     * @param redsysRefund Refund Object params
     */
    public payInsRedsysRedsysPostRefund(payInId: number, redsysRefund?: models.RedsysRefundPost, extraHttpRequestParams?: any): Observable<models.RedsysRefundResponse> {
        return this.payInsRedsysRedsysPostRefundWithHttpInfo(payInId, redsysRefund, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * View a Redsys payment
     * 
     * @param payInId The Id of a payment
     */
    public payInsRedsysRedsysGetPaymentWithHttpInfo(payInId: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v2.01/PayInsRedsys/payments/${PayInId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'payInId' is not null or undefined
        if (payInId === null || payInId === undefined) {
            throw new Error('Required parameter payInId was null or undefined when calling payInsRedsysRedsysGetPayment.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * View a Redsys Preauthorization
     * 
     * @param preauthorizationId The Id of a Redsys Preauthorization
     */
    public payInsRedsysRedsysGetPreauthorizationWithHttpInfo(preauthorizationId: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v2.01/PayInsRedsys/preauthorizations/${PreauthorizationId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'preauthorizationId' is not null or undefined
        if (preauthorizationId === null || preauthorizationId === undefined) {
            throw new Error('Required parameter preauthorizationId was null or undefined when calling payInsRedsysRedsysGetPreauthorization.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Create a Redsys PayIn Request
     * Prepares a payment on Redsys. The data returned is used to show the Redsys interface to the user.  Once the payment is done, the user will be redirected to one of UrlOk or UrlKo passed parameters.  In order to redirect the user, a Post request with Content-Type of application/x-www-form-urlencoded must be executed from the user&#39;s browser.  Below there is an example of a request where the params surrounded by curly braces have to be replaced with the response&#39;s params.  curl -X POST -H \&quot;Content-Type: application/x-www-form-urlencoded\&quot; -H \&quot;Accept: text/html,application/xhtml+xml,application/xml;q&#x3D;0.9,image/webp,*_/_*;q&#x3D;0.8\&quot; -H \&quot;Cache-Control: no-cache\&quot; -H \&quot;Postman-Token: c313f10b-0de1-227e-53d2-f721f25cd79d\&quot; -d &#39;Ds_SignatureVersion&#x3D;{Ds_SignatureVersion}&amp;amp;Ds_MerchantParameters&#x3D;{Ds_MerchantParameters}&amp;amp;Ds_Signature&#x3D;{Ds_Signature}&#39; \&quot;{Url}\&quot;
     * @param redsysPayIn Redsys PayIn Request Object params
     */
    public payInsRedsysRedsysPostPaymentByWebWithHttpInfo(redsysPayIn?: models.RedsysPayByWebPost, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v2.01/PayInsRedsys/payments/web`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json', 
            'text/json', 
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: redsysPayIn == null ? '' : JSON.stringify(redsysPayIn), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Create a Redsys Preauthorization Request
     * Prepares a preauthorization on Redsys. The data returned is used to show the Redsys interface to the user.  Once the preauthoriation is done, the user will be redirected to one of UrlOk or UrlKo passed parameters.  In order to redirect the user, a Post request with Content-Type of application/x-www-form-urlencoded must be executed from the user&#39;s browser.  Below there is an example of a request where the params surrounded by curly braces have to be replaced with the response&#39;s params.  curl -X POST -H \&quot;Content-Type: application/x-www-form-urlencoded\&quot; -H \&quot;Accept: text/html,application/xhtml+xml,application/xml;q&#x3D;0.9,image/webp,*_/_*;q&#x3D;0.8\&quot; -H \&quot;Cache-Control: no-cache\&quot; -H \&quot;Postman-Token: c313f10b-0de1-227e-53d2-f721f25cd79d\&quot; -d &#39;Ds_SignatureVersion&#x3D;{Ds_SignatureVersion}&amp;amp;Ds_MerchantParameters&#x3D;{Ds_MerchantParameters}&amp;amp;Ds_Signature&#x3D;{Ds_Signature}&#39; \&quot;{Url}\&quot;
     * @param redsysPreauthorization RedsysPreauthorization Object params
     */
    public payInsRedsysRedsysPostPreauthorizationByWebWithHttpInfo(redsysPreauthorization?: models.RedsysPreauthorizeByWebPost, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v2.01/PayInsRedsys/preauthorizations/web`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json', 
            'text/json', 
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: redsysPreauthorization == null ? '' : JSON.stringify(redsysPreauthorization), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Cancels a Preauthorization
     * 
     * @param preauthorizationId The Id of a Redsys PreauthorizationCancellation
     * @param redsysPreauthorizationCancellation PreauthorizationCancellation Object params
     */
    public payInsRedsysRedsysPostPreauthorizationCancellationWithHttpInfo(preauthorizationId: number, redsysPreauthorizationCancellation?: models.RedsysPreauthorizationCancellationPost, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v2.01/PayInsRedsys/preauthorizations/${PreauthorizationId}/cancellation`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'preauthorizationId' is not null or undefined
        if (preauthorizationId === null || preauthorizationId === undefined) {
            throw new Error('Required parameter preauthorizationId was null or undefined when calling payInsRedsysRedsysPostPreauthorizationCancellation.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json', 
            'text/json', 
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: redsysPreauthorizationCancellation == null ? '' : JSON.stringify(redsysPreauthorizationCancellation), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Confirms a Preauthorization
     * 
     * @param preauthorizationId The Id of a Redsys PreauthorizationConfirmation
     * @param redsysPreauthorizationConfirmation PreauthorizationConfirmation Object params
     */
    public payInsRedsysRedsysPostPreauthorizationConfirmationWithHttpInfo(preauthorizationId: number, redsysPreauthorizationConfirmation?: models.RedsysPreauthorizationConfirmationPost, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v2.01/PayInsRedsys/preauthorizations/${PreauthorizationId}/confirmation`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'preauthorizationId' is not null or undefined
        if (preauthorizationId === null || preauthorizationId === undefined) {
            throw new Error('Required parameter preauthorizationId was null or undefined when calling payInsRedsysRedsysPostPreauthorizationConfirmation.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json', 
            'text/json', 
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: redsysPreauthorizationConfirmation == null ? '' : JSON.stringify(redsysPreauthorizationConfirmation), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Create a Redsys Payment Refund
     * A PayIn Refund is a request to reimburse a user on their payment card. The money which has already been paid will automatically go back to the user’s bank account.              Minimum amount to refund is 1€.              If you&#39;re doing a partial Refund, note that you can only refund the same amount on the same transaction once per day (this is to prevent unintended duplicate refunds). After 24h you can do another refund of the same amount on the same transaction. If it is a different amount on the same transaction, there is not this limit.              If you do not specify DebitedFunds and Fees parameters, it will automatically fully refund the PayIn. However if you do provide one or the other, you must provide both. Note that Fees must be negative if you wish to refund them - adding a positive value for the Fees is a way to charge your customers for the Refund (in the same way you might for a PayIn, Transfer or any other Transaction
     * @param payInId The Id of a PayIn
     * @param redsysRefund Refund Object params
     */
    public payInsRedsysRedsysPostRefundWithHttpInfo(payInId: number, redsysRefund?: models.RedsysRefundPost, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v2.01/PayInsRedsys/payments/${PayInId}/refunds`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'payInId' is not null or undefined
        if (payInId === null || payInId === undefined) {
            throw new Error('Required parameter payInId was null or undefined when calling payInsRedsysRedsysPostRefund.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json', 
            'text/json', 
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: redsysRefund == null ? '' : JSON.stringify(redsysRefund), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
